sudo: required
services:
  - docker

before_install:
  - docker build -t tarabet/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true tarabet/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "tarabet-react-docker"
  env: "TarabetReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-711190079749"
  bucket_path: "tarabet-react-docker"

  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
